export const CARE_LIST_REQUEST = 'CARE_LIST_REQUEST'
export const CARE_LIST_SUCCESS = 'CARE_LIST_SUCCESS'
export const CARE_LIST_FAIL = 'CARE_LIST_FAIL'

export const CARE_DETAILS_REQUEST = 'CARE_DETAILS_REQUEST'
export const CARE_DETAILS_SUCCESS = 'CARE_DETAILS_SUCCESS'
export const CARE_DETAILS_FAIL = 'CARE_DETAILS_FAIL'

export const CARE_DELETE_REQUEST = 'CARE_DELETE_REQUEST'
export const CARE_DELETE_SUCCESS = 'CARE_DELETE_SUCCESS'
export const CARE_DELETE_FAIL = 'CARE_DELETE_FAIL'

export const CARE_CREATE_REQUEST = 'CARE_CREATE_REQUEST'
export const CARE_CREATE_SUCCESS = 'CARE_CREATE_SUCCESS'
export const CARE_CREATE_FAIL = 'CARE_CREATE_FAIL'
export const CARE_CREATE_RESET = 'CARE_CREATE_RESET'

export const CARE_UPDATE_REQUEST = 'CARE_UPDATE_REQUEST'
export const CARE_UPDATE_SUCCESS = 'CARE_UPDATE_SUCCESS'
export const CARE_UPDATE_FAIL = 'CARE_UPDATE_FAIL'
export const CARE_UPDATE_RESET = 'CARE_UPDATE_RESET'
