// fanpageConstants.js

export const FANPAGE_FOLLOW_REQUEST = 'FANPAGE_FOLLOW_REQUEST';
export const FANPAGE_FOLLOW_SUCCESS = 'FANPAGE_FOLLOW_SUCCESS';
export const FANPAGE_FOLLOW_FAIL = 'FANPAGE_FOLLOW_FAIL';

export const FANPAGE_UNFOLLOW_REQUEST = 'FANPAGE_UNFOLLOW_REQUEST';
export const FANPAGE_UNFOLLOW_SUCCESS = 'FANPAGE_UNFOLLOW_SUCCESS';
export const FANPAGE_UNFOLLOW_FAIL = 'FANPAGE_UNFOLLOW_FAIL';

export const FANPAGE_CREATE_REQUEST = 'FANPAGE_CREATE_REQUEST';
export const FANPAGE_CREATE_SUCCESS = 'FANPAGE_CREATE_SUCCESS';
export const FANPAGE_CREATE_FAIL = 'FANPAGE_CREATE_FAIL';

export const FANPAGE_FOLLOWED_FETCH_REQUEST = 'FANPAGE_FOLLOWED_FETCH_REQUEST';
export const FANPAGE_FOLLOWED_FETCH_SUCCESS = 'FANPAGE_FOLLOWED_FETCH_SUCCESS';
export const FANPAGE_FOLLOWED_FETCH_FAIL = 'FANPAGE_FOLLOWED_FETCH_FAIL';
